### ISSUE TITLE
Monitor public chargers?

### ISSUE THREAD

**Issue by dheera** [mbillow/ha-chargepoint#31]
For those of us that live in apartment complexes with a few shared chargers, any possibility of being able to monitor these chargers to know if there is one available?

**Comment by mbillow** [comment]
It’s definitely possible. I’m not sure there is a user friendly way of getting the charger IDs that would be needed to set this up, though. 

The only way I’ve been able to find them in the past is to MITM the app as it’s making API requests. I guess we could take map coordinates and use the map search API. We’d need to support that API in the Python ChargePoint library though.

Is this something you’re interested in working on or just a feature request?

**Comment by dheera** [comment]
Might be interested if it fits into the existing framework. The other thing I imagine is the public chargers probably don't need any credentials?

**Comment by dheera** [comment]
![2023-09-22_03-32](https://github.com/mbillow/ha-chargepoint/assets/1786477/18de6c3b-d157-49d9-ae1f-d51011873d71)
I think the charger IDs can be gotten from the website by clicking on a charger and looking at the URL.

**Comment by mbillow** [comment]
> Might be interested if it fits into the existing framework.

The API to check private chargers isn’t any different than public ones, there are just permissions that prevent anyone else from checking the status of private chargers.

> The other thing I imagine is the public chargers probably don't need any credentials?

It would complicate the config flow a bit, but we could ask if a user needs to monitor a private (via Connections) or home charger before asking for credentials.

> I think the charger IDs can be gotten from the website by clicking on a charger and looking at the URL.

Good find. If you end up contributing, make sure you include this in the README. 🙂

**Comment by MoFa85** [comment]
Hi there,
just found this great HA integration and was hoping it's able to display the public chargers, too...
Maybe there's an easier way by polling the favorities in HA? I've marked a couple of public charge points as favorities. Can you feth that data from the account.
This way the authentication method would be kept as is and any charge points that you're interested in just have to be setup within the account :-)

**Comment by chilicheech** [comment]
Interested in monitoring public chargers as well and I like the idea of it using the favorites. However, manually inputing the IDs is also good.

Another thing I'd like to be able to do is to have a switch to `Stop Session` whether I'm using a monitored or unmonitored charger.

**Comment by MoFa85** [comment]
Hi @chilicheech 
I am using the chargecloud integration for this feature
![grafik](https://github.com/user-attachments/assets/01674770-b319-40c4-9739-5ef47028d7cf)
Works like a charm.
![grafik](https://github.com/user-attachments/assets/71b9fd04-df32-4591-997d-f41aa21d23b3)
Gives back "CHARGING" or "AVAILABLE"

**Comment by cannondale0815** [comment]
+1 for the idea of using public IDs for this

**Comment by bb17660** [comment]
Hey, just now got this running on my home CPH50 (yay!)... 
But as the likely admin for a group of public chargers to be installed in a condo complex (two dual-port CPF50s). Wondering if this should “just work” with the admin credentials?

FYI: Looking to have a notification for the property manager when someone is idle for too long (plugged in, no power for XX min) , but also…. maaybe in combination with a parking sensor to know if someone is ICE-ing the spot (parked + not plugged in for XX min. = Call a Tow Truck!).

**Comment by mbillow** [comment]
Home chargers have their own APIs, so even giving this plugin public charger management credentials won’t surface public chargers. 

Being completely transparent, I don’t have a lot of interest in using something like this, so I don’t have a lot of ambition to write the code. I’m more than happy to review and merge the changes if someone wants them though! 🙂

**Comment by PanicRide** [comment]
If I get an opportunity in the next couple months, I'd love to take a stab at this.

When I found there was a ChargePoint integration, I was disappointed to see that it's limited to just the home station features. I only use ChargePoint stations at the office and I really want something that can help me join the waitlist. On their website app, they support the ability to draw a rectangle on the map to create a custom waitlist that you can then join from anywhere. However, you can't manage or join those custom waitlists from the Android app, so it requires logging in to the website every time, and those logins only last a few hours.

Since both the residential and commercial features use the same account login, I'm hoping it will be possible to just expand this existing integration instead of creating a new one. :)

**Comment by therealcmj** [comment]
@PanicRide and @mbillow 

FYI this is doable without any Python code by using the RESTful sensor built into Home Assistant

Open your HA config and edit configuration.yaml and pop this in there, updating as necessary if you'd like to monitor a station different from the one I'm interested in. Then do a **full restart** (a quick reload of YAML doesn't pick this up)

```
rest:
  # Chargepoint public station status
  # 1. go to https://driver.chargepoint.com/
  # 2. locate the charger you want and click on it
  #    the URL will update to something like https://driver.chargepoint.com/stations/124429
  # 3. grab that number and put it in the URL below
  # 4. update this as necessary
  #    in the case of the station I monitor (124429) there are 2 ports.
  #    I add 2 sensors to my HA setup - one for each side
  - resource: "https://mc.chargepoint.com/map-prod/v3/station/info?deviceId=124429"
    sensor:
    # this is a demo showing super basics of pulling a field from the JSON payload
    #   - name: "resttest"
    #     value_template: "{{ value_json['deviceId'] }}"
        
      - name: "ChargePoint MPL Entrance Left"
        value_template: "{{ value_json['portsInfo']['ports'][0]['status'] }}"

      - name: "ChargePoint MPL Entrance Right"
        value_template: "{{ value_json['portsInfo']['ports'][1]['status'] }}"

```
