### ISSUE TITLE
“Last connected at” doesn’t update 

### ISSUE THREAD

**Issue by snairolf** [mbillow/ha-chargepoint#33]

**Comment by adamblais** [comment]
+1 Same issue here

**Comment by ultimateguy** [comment]
+1 Same issue here

**Comment by dmzimmerman** [comment]
I see what I assume is the same issue. It says my "last connected at" is back in February, but also says it's online now, and I know for a fact that it's lost wifi connectivity at least once between then and now.

**Comment by sxdjt** [comment]
+1 

It seems to work properly when plugging in, but some time after the charging cycle is complete, it goes to "Unknown" status and stops updating.

<img width="433" alt="Screenshot 2023-12-29 at 02 31 32" src="https://github.com/mbillow/ha-chargepoint/assets/53812540/fe002d1d-e158-4682-b0c1-3504f6d0a7ce">

**Comment by sxdjt** [comment]
The "Last Connected" entry in the logbook says it was in 1969, which may be a problem?

'Last Connected At changed to December 31, 1969 at 4:00 PM 2:34:48 AM - 3 minutes ago'

<img width="327" alt="Screenshot 2023-12-29 at 02 37 09" src="https://github.com/mbillow/ha-chargepoint/assets/53812540/8bc2b168-6e01-4b18-ae7f-7c8219e82e45">


FWIW, here is my card configuration:

```
type: entities
entities:
  - entity: sensor.cph50_charger_state
    secondary_info: last-updated
  - entity: sensor.cph50_charge_cost
    secondary_info: last-updated
  - entity: sensor.cph50_charging_cable
    secondary_info: last-updated
  - entity: sensor.cph50_charging_status
    secondary_info: last-updated
  - entity: sensor.cph50_energy_output
    secondary_info: last-updated
  - entity: sensor.cph50_miles_hour_added
    secondary_info: last-updated
  - entity: sensor.cph50_miles_added
    secondary_info: last-updated
  - entity: sensor.cph50_network
    secondary_info: last-updated
  - entity: sensor.cph50_power_output
    secondary_info: last-updated
title: Car Charger
state_color: true
```

...and the info on the Chargepoint from the integration config screen:

```
CPH50-Hardwire-L23
by ChargePoint
Firmware: 5.5.3.13 
```
